# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DrugiProjektDialog
                                 A QGIS plugin
 wtyczka na zajecia z informatyki
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-05
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Mateusz Jankowski Kacper Kedra 
        email                : mateusz2001.pl@wp.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Drugi_Projekt_dialog_base.ui'))


class DrugiProjektDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DrugiProjektDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushButton_zlicz_elementy.clicked.connect(self.zlicz_elementy)
        self.radioButton_pole.clicked.connect(self.obliczanie)
        self.radioButton_przewyzszenia.clicked.connect(self.obliczanie)

    def obliczanie(self):
        aktywna_warstwa = iface.activeLayer()
        zliczanie_obiektow = aktywna_warstwa.selectedFeatureCount()
        X = []
        Y = []
        Z = []
        nr = []
        for punkt in aktywna_warstaw.selectedFeatureCount():
            x.append(punkt[" x_92 "])
            y.append(punkt[" y_92 "])
            z.append(punkt[" z_92 "])
            nr.append(punkt[" nr "])
            
        If self.redioButton.isChecked() == Trude and zliczenie_obiektow
            dh = z[1] -z[0]
            punkt_1 = nr[0]
            punkt_2 = nr[1]
            inface.messageBar().pushMessage("przewyzszenie wysokosci miedzy punktem" '+str(punkt_1)+ 'a punktem 'str(punkt_2)+'radioButton_pole)
            
        elif self.radioButton_pole.isChecked()  == True and zliczanie_obiektow >2:
            punkty = []
            for i in range(0, len(x)):
                punkty.append([x[i], y[i] ])
            p = 0
            for i in range(len(punkty)):
                if i ==len(punkty) - 1:
                    p += (punkty[i][0]+ punkty[0][0]) * (punkty[i][1] - punkty[0][1])
                else:
                    p += (punkty[i][0] + punkty[i + 1][0]) * (punkty)
                    
        
   
    
    