# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Drugi_Projekt_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrugiProjektDialogBase(object):
    def setupUi(self, DrugiProjektDialogBase):
        DrugiProjektDialogBase.setObjectName("DrugiProjektDialogBase")
        DrugiProjektDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(DrugiProjektDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pushButton_zlicz_elementy = QtWidgets.QPushButton(DrugiProjektDialogBase)
        self.pushButton_zlicz_elementy.setGeometry(QtCore.QRect(120, 80, 75, 23))
        self.pushButton_zlicz_elementy.setObjectName("pushButton_zlicz_elementy")
        self.label_lb_elementow = QtWidgets.QLabel(DrugiProjektDialogBase)
        self.label_lb_elementow.setGeometry(QtCore.QRect(240, 100, 131, 21))
        self.label_lb_elementow.setText("")
        self.label_lb_elementow.setObjectName("label_lb_elementow")
        self.mMapLayerComboBox = QgsMapLayerComboBox(DrugiProjektDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(60, 160, 160, 27))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")

        self.retranslateUi(DrugiProjektDialogBase)
        self.button_box.accepted.connect(DrugiProjektDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(DrugiProjektDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DrugiProjektDialogBase)

    def retranslateUi(self, DrugiProjektDialogBase):
        _translate = QtCore.QCoreApplication.translate
        DrugiProjektDialogBase.setWindowTitle(_translate("DrugiProjektDialogBase", "Drugi Projekt"))
        self.pushButton_zlicz_elementy.setText(_translate("DrugiProjektDialogBase", "zlicz elementy"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DrugiProjektDialogBase = QtWidgets.QDialog()
    ui = Ui_DrugiProjektDialogBase()
    ui.setupUi(DrugiProjektDialogBase)
    DrugiProjektDialogBase.show()
    sys.exit(app.exec_())
