# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Drugi_Projekt_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrugiProjektDialogBase(object):
    def setupUi(self, DrugiProjektDialogBase):
        DrugiProjektDialogBase.setObjectName("DrugiProjektDialogBase")
        DrugiProjektDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(DrugiProjektDialogBase)
        self.button_box.setGeometry(QtCore.QRect(20, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.radioButton_pole = QtWidgets.QRadioButton(DrugiProjektDialogBase)
        self.radioButton_pole.setGeometry(QtCore.QRect(100, 170, 111, 31))
        self.radioButton_pole.setObjectName("radioButton_pole")
        self.radioButton_przewyzszenia = QtWidgets.QRadioButton(DrugiProjektDialogBase)
        self.radioButton_przewyzszenia.setGeometry(QtCore.QRect(100, 140, 121, 31))
        self.radioButton_przewyzszenia.setObjectName("radioButton_przewyzszenia")
        self.label = QtWidgets.QLabel(DrugiProjektDialogBase)
        self.label.setGeometry(QtCore.QRect(110, 50, 141, 20))
        self.label.setObjectName("label")
        self.mMapLayerComboBox = QgsMapLayerComboBox(DrugiProjektDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(100, 80, 160, 27))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.zlicz_elementy = QtWidgets.QPushButton(DrugiProjektDialogBase)
        self.zlicz_elementy.setGeometry(QtCore.QRect(50, 230, 75, 23))
        self.zlicz_elementy.setObjectName("zlicz_elementy")
        self.zlicz_elementy_wynik = QtWidgets.QLabel(DrugiProjektDialogBase)
        self.zlicz_elementy_wynik.setGeometry(QtCore.QRect(60, 260, 47, 13))
        self.zlicz_elementy_wynik.setText("")
        self.zlicz_elementy_wynik.setObjectName("zlicz_elementy_wynik")

        self.retranslateUi(DrugiProjektDialogBase)
        self.button_box.accepted.connect(DrugiProjektDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(DrugiProjektDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DrugiProjektDialogBase)

    def retranslateUi(self, DrugiProjektDialogBase):
        _translate = QtCore.QCoreApplication.translate
        DrugiProjektDialogBase.setWindowTitle(_translate("DrugiProjektDialogBase", "Drugi Projekt"))
        self.radioButton_pole.setText(_translate("DrugiProjektDialogBase", "pole powierzchni"))
        self.radioButton_przewyzszenia.setText(_translate("DrugiProjektDialogBase", "Przewyższenia"))
        self.label.setText(_translate("DrugiProjektDialogBase", "Wybierz aktywna warstwe"))
        self.zlicz_elementy.setText(_translate("DrugiProjektDialogBase", "Zlicz elementy"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DrugiProjektDialogBase = QtWidgets.QDialog()
    ui = Ui_DrugiProjektDialogBase()
    ui.setupUi(DrugiProjektDialogBase)
    DrugiProjektDialogBase.show()
    sys.exit(app.exec_())
